
twitter:
  consumer_key: "UjwtjLkQDn3fbmS1jN1Yhb99R"
  consumer_secret: "JfsDcBWAInOVbq1uJplEVpzFEVdhvY2pmpA7TLXZ5qZ9AXxlxg"
  access_token: "790140278506217472-pgWkxH7Fynax6GMh0hfGfu2F9q9P0MF"
  access_secret: "IT6buN6Th1Khn5M8NxlFkRUd8QhXMQMkWjAgh0h0u8wQn"



spotify:
  client_id: "37abf8ddd28d43e18336e02375dc233e"
  client_secret: "52667304a4ab40bf8b8e467f78a559bc"
